# Generated by Django 2.0.4 on 2018-04-15 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    atomic = False

    operations = [
        migrations.CreateModel(
            name='Howto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('howto_step', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='recipes',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='imgPath',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='recipe_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='time',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='howto',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Recipes'),
        ),
    ]
