# Generated by Django 2.0.4 on 2018-04-16 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ingredients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
