# Generated by Django 2.0.4 on 2018-04-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180416_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ManyToManyField(related_name='recipe', to='api.Recipe'),
        ),
    ]
