# Generated by Django 2.0.4 on 2018-04-19 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180419_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_pk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='book1', to='api.Author'),
        ),
    ]
