# Generated by Django 2.0.4 on 2018-04-20 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180419_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_pk',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
