# Generated by Django 2.0.4 on 2018-04-20 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180420_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_id',
        ),
    ]
