# Generated by Django 2.0.4 on 2018-04-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='recipe',
            name='portion',
            field=models.IntegerField(default=0),
        ),
    ]
