# Generated by Django 2.0.4 on 2018-04-25 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20180425_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400)),
                ('imgPath', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='category_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_key', to='api.Category'),
        ),
    ]
